import { Kysely, PostgresDialect } from "kysely";
import { Pool, types as pgTypes } from "pg";
// `db.types.ts` is generated by `pnpm db:codegen` — see scripts/codegen.ts.
// Falls back to `{}` until the first codegen run lands, so this file can be
// imported during the bootstrap migration before any tables exist.
import type { DB } from "./db.types";

// PostgreSQL DATE OID = 1082. By default node-pg parses these into JS Date
// objects at UTC midnight, which means an invoice dated 2026-03-10 surfaces
// as "2026-03-09T23:00:00.000Z" in any tz east of Greenwich. Keep DATE
// values as their YYYY-MM-DD string instead — the codegen step uses
// `--date-parser string` so the static type matches what the driver
// returns. TIMESTAMPTZ (1184) stays a Date because it's a real moment.
pgTypes.setTypeParser(1082, (val) => val);

export type Database = DB;

/**
 * Build a Kysely instance bound to a fresh pg Pool.
 *
 * On the Worker we create one per request — pg holds no useful state across
 * Worker invocations and the connection actually goes to Neon's pooler. On
 * Node (migrations, codegen) the caller owns the pool's lifecycle and is
 * expected to `await db.destroy()` before exiting.
 */
export function createDb(connectionString: string): Kysely<Database> {
  return new Kysely<Database>({
    dialect: new PostgresDialect({
      pool: new Pool({ connectionString, max: 1 }),
    }),
  });
}
