/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Bill {
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  dueDate: string | null;
  fileKey: string;
  fileName: string;
  id: string;
  invoiceDate: string | null;
  invoiceNumber: string | null;
  organizationId: string;
  rawExtract: Json | null;
  status: Generated<string>;
  subtotalMinor: Int8 | null;
  supplierId: string | null;
  totalMinor: Int8 | null;
  uploadedByUserId: string;
  vatMinor: Int8 | null;
}

export interface BillLineItem {
  amountMinor: Int8;
  billId: string;
  description: string;
  id: string;
  lineNo: number;
  quantity: Numeric | null;
  unitPriceMinor: Int8 | null;
}

export interface Invitation {
  email: string;
  expiresAt: Timestamp;
  id: string;
  inviterId: string;
  organizationId: string;
  role: string;
  status: Generated<string>;
}

export interface JournalEntry {
  billId: string;
  createdAt: Generated<Timestamp>;
  decidedAt: Timestamp | null;
  decidedByUserId: string | null;
  id: string;
  reasoning: string | null;
  status: Generated<string>;
}

export interface JournalEntryPosting {
  accountCode: string;
  accountName: string;
  creditMinor: Generated<Int8>;
  debitMinor: Generated<Int8>;
  id: string;
  journalEntryId: string;
  lineNo: number;
}

export interface Member {
  createdAt: Generated<Timestamp>;
  id: string;
  organizationId: string;
  role: Generated<string>;
  userId: string;
}

export interface Organization {
  createdAt: Generated<Timestamp>;
  id: string;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface Session {
  activeOrganizationId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
  userId: string;
}

export interface Supplier {
  createdAt: Generated<Timestamp>;
  id: string;
  name: string;
  organizationId: string;
  orgNumber: string | null;
  updatedAt: Generated<Timestamp>;
  vatNumber: string | null;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: Generated<boolean>;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp | null>;
  value: string;
}

export interface DB {
  account: Account;
  bill: Bill;
  billLineItem: BillLineItem;
  invitation: Invitation;
  journalEntry: JournalEntry;
  journalEntryPosting: JournalEntryPosting;
  member: Member;
  organization: Organization;
  session: Session;
  supplier: Supplier;
  user: User;
  verification: Verification;
}
