import { Kysely, PostgresDialect } from "kysely";
import { Pool } from "pg";
// `db.types.ts` is generated by `pnpm db:codegen` — see scripts/codegen.ts.
// Falls back to `{}` until the first codegen run lands, so this file can be
// imported during the bootstrap migration before any tables exist.
import type { DB } from "./db.types";

export type Database = DB;

/**
 * Build a Kysely instance bound to a fresh pg Pool.
 *
 * On the Worker we create one per request — pg holds no useful state across
 * Worker invocations and the connection actually goes to Neon's pooler. On
 * Node (migrations, codegen) the caller owns the pool's lifecycle and is
 * expected to `await db.destroy()` before exiting.
 */
export function createDb(connectionString: string): Kysely<Database> {
  return new Kysely<Database>({
    dialect: new PostgresDialect({
      pool: new Pool({ connectionString, max: 1 }),
    }),
  });
}
